# ============================================================================
# mantou 多阶段构建
#   阶段 1  web-builder : 用 Node 构建 Vue 前端，产出 web/dist
#   阶段 2  go-builder  : 将 dist 内嵌进 Go 二进制，静态编译
#   阶段 3  runtime     : 极简运行镜像，仅包含二进制与运行期依赖
#
# 多架构（buildx --platform linux/amd64,linux/arm64）下前两个阶段都钉在构建机架构上，
# 靠 Go 交叉编译产出目标架构的二进制，全程不进 QEMU；只有阶段 3 是目标架构。
# 详见各阶段 FROM 行上方的说明。
#
# 网络受限时可切换镜像源，例如：
#   docker build \
#     --build-arg MIRROR=docker.1ms.run/library/ \
#     --build-arg GOPROXY=https://goproxy.cn,direct \
#     --build-arg NPM_REGISTRY=https://registry.npmmirror.com .
#
#   - MIRROR        : 基础镜像前缀（加速站），结尾需带 / ；为空则走 docker.io
#   - GOPROXY       : Go 模块代理，为空回退到官方代理 + direct
#   - NPM_REGISTRY  : npm 镜像源，为空则走官方源
# ============================================================================

ARG MIRROR=
# Go 模块代理与 npm 镜像（默认走官方源；国内/受限网络覆盖为镜像，见下方各阶段 ENV）。
ARG GOPROXY=
ARG NPM_REGISTRY=

# ---------- 阶段 1：构建前端 ----------
# node:22-alpine：Node 20 已于 2026-04 结束维护（不再收安全补丁），故抬到 22（LTS，维护至 2027-04）。
#
# --platform=$BUILDPLATFORM 是多架构构建的关键：钉在**构建机**的架构上，不跟目标架构走。
# 前端产物是 JS / CSS / HTML，与 CPU 架构无关，两个目标架构本可以共用同一份。
# 不钉的话 buildx 会为 linux/arm64 再跑一遍这个阶段，而 amd64 的构建机上那一遍是在
# QEMU 模拟的 aarch64 里跑的——npm ci 全是 fork/exec 和小文件读写，正是模拟最慢的一类负载，
# 实测会从一分多钟变成几十分钟甚至看起来像卡死。钉上之后这个阶段只跑一次，且是原生速度。
FROM --platform=$BUILDPLATFORM ${MIRROR}node:22-alpine AS web-builder
WORKDIR /web

# 重新声明以便在本阶段 RUN 中使用传入的构建参数（全局 ARG 仅在 FROM 行可见）
ARG NPM_REGISTRY

# 先只拷贝依赖清单以复用缓存层
COPY web/package.json web/package-lock.json* ./

# 受限网络下可传入 --build-arg NPM_REGISTRY=https://registry.npmmirror.com
# 传入后所有 npm 安装均走该镜像；为空则使用官方源。
RUN if [ -n "$NPM_REGISTRY" ]; then npm config set registry "$NPM_REGISTRY"; fi \
    && npm ci

# 再拷贝源码并构建
COPY web/ ./
RUN npm run build:only

# ---------- 阶段 2：构建后端 ----------
# golang:1.26-alpine：Go 1.22 早已结束维护（官方只支持最近两个大版本），继续用它构建意味着
# 二进制里静态链接的是一个不再接收安全补丁的标准库——net/http、crypto/tls 的漏洞修复都拿不到。
# 版本下限同时由 go.mod 的 go 指令（1.25.0）约束，此处取更高的 1.26 以获得最新补丁。
FROM --platform=$BUILDPLATFORM ${MIRROR}golang:1.26-alpine AS go-builder
WORKDIR /src

# 构建缓存加速（可选）
ENV CGO_ENABLED=0 \
    GOFLAGS=-buildvcs=false

# Go 模块代理：默认走官方源，受限网络可传入
# --build-arg GOPROXY=https://goproxy.cn,direct 走国内镜像。
# 若为空则回退到官方代理 + direct（即直接在模块源拉取）。
ARG GOPROXY
ENV GOPROXY=${GOPROXY:-https://proxy.golang.org,direct}

# 先拷贝模块清单（go.sum 已随仓库提交，构建期不再改动它）
COPY go.mod go.sum ./

# 按 go.mod/go.sum 精确下载依赖。刻意不用 go mod tidy：
#   1. tidy 会**改写** go.mod/go.sum，等于让构建结果取决于构建当天上游的可解析版本，
#      同一份源码在不同时间可能链接进不同的依赖版本，go.sum 的校验意义被抵消；
#   2. tidy 需要扫描全部源码，无法在只拷贝清单的这一层命中缓存，每次改代码都要重下依赖。
# 这一层单独放在拷贝源码之前，依赖清单不变时可直接复用缓存。
# -mod=readonly（Go 1.16 起为默认）令任何 go.mod/go.sum 不一致都在此处显式报错，
# 而不是被静默"修好"。
RUN go mod download -x

# 交叉编译目标。TARGETOS / TARGETARCH 由 buildx 依 --platform 自动注入，需在本阶段
# 重新声明才能在 ENV 里引用；用普通 docker build（不带 --platform）时两者为空，
# Go 会回退到构建机的原生架构，本地单架构构建的行为不变。
#
# 刻意放在 go mod download 之后：模块下载与目标平台无关，放在前面会让两个目标架构
# 各自算出不同的层缓存键、把依赖重下一遍。摆在这里，两者共用同一个下载层，
# 只在真正 go build 时才分叉。
ARG TARGETOS
ARG TARGETARCH
ENV GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH}

# 拷贝全部后端源码
COPY cmd/ ./cmd/
COPY internal/ ./internal/
COPY web/embed.go ./web/embed.go

# 用阶段 1 的前端产物覆盖占位 dist（embed 依赖 web/dist 存在）
COPY --from=web-builder /web/dist ./web/dist

# 版本号 / 编译时间直接在构建期写入 internal/version/gen.go（与 version.go 同包，
# 通过 init() 覆盖 version.go 中的包级变量）。刻意不用 -ldflags -X：版本号含空格时
# 会被 shell/链接器拆断，需额外 Base64/URL 编码。改为把值以 Go 字符串字面量直接写
# 进源码，空格原样保留；运行时无需解析任何文件，异常在编译期即被拦下。直接
# go build / go run（无 gen.go）时，version.go 的默认值与文件修改时间回退仍生效。
ARG VERSION="Ver 0.0.0"
RUN printf 'package version\n\n// Code generated by the build script. DO NOT EDIT.\nfunc init() {\n\tVersion = "%s"\n\tBuildTime = "%s"\n}\n' \
    "${VERSION}" "$(date '+%Y-%m-%d %H:%M:%S')" > internal/version/gen.go
RUN go build -trimpath -mod=readonly \
    -ldflags "-s -w" \
    -o /out/mantou ./cmd/mantou

# ---------- 阶段 3：运行镜像 ----------
# 这一阶段**刻意不钉** --platform：它就是最终要发出去的那个镜像，必须是目标架构。
# 唯一在模拟下跑的是下面那句 apk add（两个包），几秒钟的事，不构成瓶颈。
#
# alpine:3.24：3.20 已于 2026-05 结束维护，ca-certificates / musl 的安全更新都停在那里；
# ACME 与 DDNS 全程依赖根证书，运行镜像的证书库过期会直接导致签发与解析更新失败。
FROM ${MIRROR}alpine:3.24 AS runtime

# 时区 + CA 证书（DDNS/ACME 走 HTTPS 需要）
RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app
COPY --from=go-builder /out/mantou /app/mantou

# 数据目录（配置、日志、上传、证书）
ENV MANTOU_DATA_DIR=/data
VOLUME ["/data"]

# 面板默认端口（可在设置中修改，修改后需重启容器）
EXPOSE 25666

# Go 运行时软内存上限。稳态只有 30~60 MB，真正的峰值来自**并发连接的转发缓冲**：
# 端口转发每条 TCP 连接约 64 KiB（收发各 32 KiB，上限 1024 条/规则），反向代理每个在传响应约 32 KiB
#（上限 2000 连接/监听端口）——打满即可达数十 MB。没有软上限时 Go 按 GOGC=100 扩张、
# 且不急于把高峰后的堆还给操作系统，容器 RSS 会长期停在峰值附近，看起来像内存泄漏。
# 设了它，堆逼近 200 MiB 就加频 GC 并归还内存。
# 这是**软**上限：超了只会更拼命 GC，不会 OOM kill，因此对内存宽裕的宿主机也无害。
# 需要更大堆（例如同时跑几百条规则）时用 `-e GOMEMLIMIT=512MiB` 覆盖即可。
ENV GOMEMLIMIT=200MiB

# 说明：mantou 的 Web 服务/端口转发模块需要绑定任意端口（含 80/443 等特权端口），
# WOL 还需二层广播，因此容器以 root 运行——这是自托管网络工具的常规做法。
# 生产部署建议使用 host 网络（见 docker-compose.yml），或按需追加 -p 映射。
ENTRYPOINT ["/app/mantou"]
CMD ["--data", "/data"]

# 刻意不写 HEALTHCHECK，容器状态就只有 running / stop 两种。
#
# 更进一步：程序里也没有任何可供外部探活的端点。这两件事是一起决定的，理由分三层。
#
# 一是那个标签不参与任何自动恢复：Docker 从不因为 unhealthy 去重启容器，MikroTik
# RouterOS 的 auto-restart-interval 也只看进程有没有退出。真正会消费它的是多容器依赖
# 启动与负载均衡摘除坏实例，而这是个单体自托管面板，没有谁在消费。
# 二是要探对地址，就得同时跟上「面板端口可改、HTTPS 可开关、访问路径前缀可配」，以及
# 各家容器运行时对 CMD-SHELL 的执行差异（是否真交给 sh -c、命令替换与变量是否展开）——
# 最后一项在 RouterOS 上既无公开文档也无法验证。探错了就是面板明明好着、容器却被标成
# unhealthy，让人去查一个不存在的故障；一个会误报的状态灯比没有状态灯更糟。
# 三是一个免鉴权的探活端点本身就是攻击面：它向任何人确认"这个端口后面有东西在跑"，
# 而这台面板的可鉴权面之外应当什么都不回。所以端点与命令行开关一并删除了，
# 不留"默认关闭、需要时打开"的余地——留着就会有人打开。
#
# 因此这里也不给注释掉的 HEALTHCHECK 示例：没有可探的地址，示例只会引人去找一个不存在的端点。
# 需要"进程活着吗"这个层面的判断，用容器运行时自己的进程状态（docker ps / RouterOS 的容器列表）。

