# ============================================================================
# mantou Makefile
#   常用目标：
#     make web        构建前端到 web/dist
#     make build      构建本机可执行文件到 bin/mantou（含前端）
#     make run        本地运行（默认数据目录 ./data）
#     make dev        前端开发服务器（热更新，代理到本地后端）
#     make docker     构建 Docker 镜像
#     make check      跑齐 CI 的 Go 门禁（gofmt + vet + build + test）
#     make tidy       go mod tidy，补全 go.sum
#     make clean      清理构建产物
# ============================================================================

APP        := mantou
VERSION    ?= Ver 1.0.0
DATA_DIR   ?= ./data
# 编译时间（默认本地时间），构建时写入 internal/version/gen.go，供「关于」页展示；
# 可覆盖：make build BUILD_TIME="2026-08-13 12:00:00"
BUILD_TIME ?= $(shell date '+%Y-%m-%d %H:%M:%S')
# 版本号与编译时间经 gen.go 在编译期写死进二进制（不依赖运行时解析文件，也不走
# -ldflags -X，避免含空格版本号被 shell/链接器拆断）。
GO         ?= go
NPM        ?= npm

# 更新包默认目标平台（make package 产物）。
# PKG_GOOS 固定 linux（容器里永远是 Linux）；PKG_ARCHS 列出要打包的 GOARCH，
# 默认同时产出 amd64 与 arm64 两个更新包，分别适配 x86_64 与 ARM（Apple Silicon /
# ARM 服务器 / 树莓派）平台的 Docker 宿主。
# 单架构覆盖：make package PKG_GOARCH=arm64（仅打该架构包，向后兼容旧用法）。
PKG_GOOS   ?= linux
PKG_GOARCH ?= amd64
PKG_ARCHS  ?= amd64 arm64
# 命令行显式指定 PKG_GOARCH 时，仅打包该架构。
ifeq ($(origin PKG_GOARCH),command line)
PKG_ARCHS  := $(PKG_GOARCH)
endif
# 更新包输出目录（默认当前目录，即执行 make 处；可覆盖：make package PKG_DIR=dist）。
PKG_DIR    ?= .
# 交叉编译时透传给 go build（make build-go 默认本机）。
GOOS       ?=
GOARCH     ?=

# 输出目录
BIN_DIR    := bin

.PHONY: all web build build-go run dev tidy docker clean fmt vet check package

all: build

## 构建前端产物（web/dist）
web:
	cd web && $(NPM) install && $(NPM) run build:only

## 补全 Go 依赖与 go.sum
tidy:
	$(GO) mod tidy

## 在构建期把版本号 / 编译时间写入 internal/version/gen.go（与 version.go 同包）。
## gen.go 通过 init() 覆盖 version.go 中的包级变量 Version / BuildTime，不重新声明
## const，因此与版本默认值无冲突；直接 go build / go run 时 version.go 的默认值生效。
## 刻意不用 -ldflags -X：版本号含空格会被 shell/链接器拆断。此处把值以 Go 字符串
## 字面量写进源码，空格原样保留，跨平台一致（GNU/BSD printf 均支持）。
write-version:
	@printf 'package version\n\n// Code generated by the build script. DO NOT EDIT.\nfunc init() {\n\tVersion = "%s"\n\tBuildTime = "%s"\n}\n' "$(VERSION)" "$(BUILD_TIME)" > internal/version/gen.go

## 构建本机二进制（先构建前端，再内嵌编译）。
## 本地构建会把版本/编译时间临时写入 gen.go 并随后删除（rm -f），保持源码干净。
build: web tidy write-version
	CGO_ENABLED=0 $(GO) build -trimpath -ldflags "-s -w" -o $(BIN_DIR)/$(APP) ./cmd/mantou
	@rm -f internal/version/gen.go
	@echo "已生成 $(BIN_DIR)/$(APP)"

## 仅编译后端（复用已有 web/dist）；GOOS/GOARCH 留空则本机。
build-go: tidy write-version
	CGO_ENABLED=0 GOOS=$(GOOS) GOARCH=$(GOARCH) $(GO) build -trimpath -ldflags "-s -w" -o $(BIN_DIR)/$(APP) ./cmd/mantou
	@rm -f internal/version/gen.go

## 打包为可被「上传更新包」消费的 tar.gz 更新包（默认双架构 amd64 + arm64）。
## 每个包内部仅含名为 mantou 的可执行文件（与 api_update.go 的 extractExecutable 约定一致）。
## 产物直接输出到当前目录（PKG_DIR，默认 .），bin/ 仅作中间二进制暂存。
## 一键执行：make package；单架构：make package PKG_GOARCH=arm64；指定输出目录：make package PKG_DIR=dist。
package: web
	@mkdir -p $(BIN_DIR)
	@$(GO) build -trimpath -o $(BIN_DIR)/updsign ./cmd/updsign
	@if [ ! -f update-signing.key ]; then \
		echo "== 生成自更新签名密钥对 =="; \
		$(BIN_DIR)/updsign gen; \
		echo; \
		echo "[重要] 请把上面输出的公钥配置到 mantou「设置 → 在线更新 → 自更新包签名公钥」"; \
		echo; \
	else \
		echo "使用已有签名私钥 update-signing.key"; \
	fi
	@for arch in $(PKG_ARCHS); do \
		$(MAKE) --no-print-directory build-go GOOS=$(PKG_GOOS) GOARCH=$$arch; \
		$(BIN_DIR)/updsign sign -key update-signing.key $(BIN_DIR)/$(APP) $(BIN_DIR)/$(APP).sig; \
		tar -czf $(PKG_DIR)/$(APP)-$(VERSION)-$(PKG_GOOS)-$$arch.tar.gz -C $(BIN_DIR) $(APP) $(APP).sig; \
		echo "已生成 $(PKG_DIR)/$(APP)-$(VERSION)-$(PKG_GOOS)-$$arch.tar.gz（可被「设置/关于 → 上传更新包」消费）"; \
	done

## 本地运行
run: build
	$(BIN_DIR)/$(APP) --data $(DATA_DIR)

## 前端开发模式（Vite 热更新，需另开终端跑后端）
dev:
	cd web && $(NPM) install && $(NPM) run dev

## 代码检查
fmt:
	$(GO) fmt ./...

vet:
	$(GO) vet ./...

## 本地一键跑齐 CI 的 Go 门禁（与 .github/workflows/ci.yml 的 go 作业一致）。
## 提交前跑一次，就不会在 CI 上因为忘了 gofmt 而红一轮。
## 注意 gofmt -l 在发现不合规文件时**仍返回 0**，所以这里显式判空再 exit 1；
## 直接写 `gofmt -l ./cmd ./internal` 当门禁等于不设防。
check:
	@echo "== gofmt =="
	@# 排除 internal/version/gen.go：构建脚本在编译前临时写入、编译后立刻删除的版本注入
	@# 文件（见 write-version），已被 .gitignore 忽略，正常情况下不存在。构建被中途打断时
	@# 它会残留在盘上，而 package.bat 用 `echo x > file` 生成——行尾必然带一个空格、缩进
	@# 也是空格而非制表符，gofmt 必报。不排除的话，门禁会指着一个你从未编辑过、也不该
	@# 提交的文件失败，非常容易误判成自己改坏了源码。
	@unformatted="$$(gofmt -l ./cmd ./internal | grep -vE 'internal[\\/]version[\\/]gen\.go$$' || true)"; \
	if [ -n "$$unformatted" ]; then \
		echo "以下文件未经 gofmt 格式化："; echo "$$unformatted"; \
		echo "请执行：gofmt -w ./cmd ./internal"; exit 1; \
	fi
	@echo "== go vet =="
	@$(GO) vet ./...
	@echo "== go build =="
	@CGO_ENABLED=0 $(GO) build -trimpath -mod=readonly ./...
	@echo "== go test =="
	@$(GO) test ./... -count=1
	@echo "全部门禁通过"

## 构建 Docker 镜像
docker:
	docker build --build-arg "VERSION=$(VERSION)" -t $(APP):"$(VERSION)" -t $(APP):latest .

## 清理
clean:
	rm -rf $(BIN_DIR) web/dist/* web/node_modules
	@# 后端用 `//go:embed all:dist` 内嵌前端产物，dist 为空目录会让 go build 直接失败。
	@# 占位文件是仓库里跟踪的 web/dist/.gitkeep（.gitignore 里有 `!web/dist/.gitkeep`）。
	@# 上面的 web/dist/* 匹配不到点开头的文件，删不掉它；这里补一次只是兜底它被手工删掉，
	@# 否则 clean 之后连 make check 都跑不起来。
	@touch web/dist/.gitkeep
	@echo "已清理构建产物（保留 web/dist 占位文件）"
