@echo off
setlocal
REM mantou update package builder (Windows equivalent of `make package`)
REM Usage: package.bat            build linux/amd64 + linux/arm64
REM        package.bat arm64     build only the given arch(es), e.g. "amd64 arm64"
REM Output: ./mantou-<VERSION>-linux-<arch>.tar.gz in current dir
REM Requires: go, node/npm, system tar (Win10+)

set APP=mantou
set VERSION=Ver 1.0.2
set BIN_DIR=bin
set PKG_GOOS=linux
if not "%~1"=="" ( set PKG_ARCHS=%~1 ) else ( set PKG_ARCHS=amd64 arm64 )

REM archive filename uses a space-free version string (avoids breaking tar on the space in VERSION)
set ARCHIVE_VER=%VERSION: =_%

REM pre-flight checks
where go >nul 2>nul || ( echo [ERR] go not found in PATH & goto :fail )
where npm >nul 2>nul || ( echo [ERR] npm not found in PATH & goto :fail )
where tar >nul 2>nul || ( echo [ERR] tar not found in PATH & goto :fail )

REM module proxy: default to a China-friendly mirror unless the user already set GOPROXY/GOSUMDB
if "%GOPROXY%"=="" set GOPROXY=https://goproxy.cn,direct
if "%GOSUMDB%"=="" set GOSUMDB=off

REM force the local toolchain: skip go's auto toolchain probe, which can emit a localized
REM "invalid switch - version" warning on Chinese Windows. Safe because installed go (1.26.6)
REM already satisfies go.mod's go directive (1.25.0).
if "%GOTOOLCHAIN%"=="" set GOTOOLCHAIN=local

REM build time (local), format yyyy-MM-dd HH:mm:ss
REM wmic localdatetime = "yyyyMMddHHmmss.uuuuuu+zzz" (14 digits before the dot).
REM Substring offsets into LD (0-based start, length):
REM   year 0,4 | month 4,2 | day 6,2 | hour 8,2 | minute 10,2 | second 12,2
REM (old ~1,2/~2,2/... offsets were off by one and yielded bogus times like 08:81:15)
for /f "skip=1 delims=. " %%i in ('wmic os get localdatetime') do set LD=%%i & goto :gotld
:gotld
set BUILD_TIME=%LD:~0,4%-%LD:~4,2%-%LD:~6,2% %LD:~8,2%:%LD:~10,2%:%LD:~12,2%

REM 1) build frontend into web/dist
pushd web
call npm install
if errorlevel 1 goto :fail
call npm run build:only
if errorlevel 1 goto :fail
popd

REM 1.5) self-update signing: build the sign tool and ensure the Ed25519 key pair exists.
REM The first run generates a random key pair and prints the public key; the private key
REM is kept in update-signing.key (never commit/share it). Later runs reuse the same key
REM so the public key configured in mantou stays valid.
if not exist %BIN_DIR% mkdir %BIN_DIR%
go build -trimpath -o %BIN_DIR%\updsign.exe ./cmd/updsign
if errorlevel 1 goto :fail
if not exist update-signing.key (
  echo == generating self-update signing key pair ==
  %BIN_DIR%\updsign.exe gen
  if errorlevel 1 goto :fail
  echo.
  echo [IMPORTANT] configure the public key printed above in mantou:
  echo   Settings -^> Online update -^> Self-update signature public key
  echo.
) else (
  echo using existing signing key: update-signing.key
)

REM 2) cross-compile + package per arch
for %%a in (%PKG_ARCHS%) do (
  call :buildone %%a
  if errorlevel 1 goto :fail
)
echo All packages built.
goto :eof

:buildone
set ARCH=%1
echo == build %PKG_GOOS%/%ARCH% ==

REM write version + build time into internal/version/gen.go (no parenthesised block:
REM the closing ) in 'func init() {' would otherwise terminate the block early).
echo package version > internal/version/gen.go
echo. >> internal/version/gen.go
echo // Code generated by the build script. DO NOT EDIT. >> internal/version/gen.go
echo func init()^ { >> internal/version/gen.go
echo   Version = "%VERSION%" >> internal/version/gen.go
echo   BuildTime = "%BUILD_TIME%" >> internal/version/gen.go
echo } >> internal/version/gen.go

REM normalise the file we just wrote: batch's `echo x >> file` also writes the space that
REM sits before the `>`, and the two lines above are indented with spaces rather than a tab,
REM so the generated gen.go is never gofmt-clean. `go fmt` fixes both in one shot.
REM Why bother for a file that is deleted a few lines below: if the build is interrupted
REM (Ctrl-C, failing `go mod tidy`, power loss) the file stays on disk, and a stray
REM unformatted gen.go makes `make check` / the CI gofmt gate fail while pointing at a file
REM the developer never edited. The gates also skip it explicitly, this is the other half.
call go fmt ./internal/version/ >nul 2>&1

call go mod tidy
if errorlevel 1 goto :fail

set CGO_ENABLED=0
set GOOS=%PKG_GOOS%
set GOARCH=%ARCH%
if not exist %BIN_DIR% mkdir %BIN_DIR%
go build -trimpath -ldflags "-s -w" -o %BIN_DIR%/%APP% ./cmd/mantou
set CGO_ENABLED=
set GOOS=
set GOARCH=
if errorlevel 1 (
  del /f internal/version/gen.go 2>nul
  goto :fail
)
del /f internal/version/gen.go

REM sign the fresh binary: Ed25519 over its SHA-256 digest (raw 64 bytes), shipped as
REM mantou.sig inside the tarball, verified by the server if Update.SignKey is configured.
%BIN_DIR%\updsign.exe sign -key update-signing.key "%BIN_DIR%\%APP%" "%BIN_DIR%\%APP%.sig"
if errorlevel 1 goto :fail

tar -czf "%APP%-%ARCHIVE_VER%-%PKG_GOOS%-%ARCH%.tar.gz" -C %BIN_DIR% %APP% %APP%.sig
if errorlevel 1 goto :fail
echo Built %APP%-%ARCHIVE_VER%-%PKG_GOOS%-%ARCH%.tar.gz
exit /b 0

:fail
echo Build failed.
exit /b 1
